kafka:
  properties:
    basic:
      auth:
        credentials:
          source: USER_INFO
          user: <<username>>
          pass: <<password>>
    enableAutoRegister: true
    max_count: 100
    max_delay: 5000
    order-topic: TP.ORDER
    schema:
      registry:
        url: http://localhost:8081
        ssl:
          truststore:
            location: kafka/certs/kafka-truststore.jks
            password: <<trust-store-pwd>>
          keystore:
            location: kafka/certs/kafka-keystore-preprod.jks
            password: <<key-store-pwd>>
          key:
            password: <<key-store-pwd>>
    ssl:
      enabled: false
      protocols: TLSv1.2,TLSv1.1,TLSv1
      truststore:
        type: JKS
        location: kafka/certs/kafka-truststore.jks
        password: <<trust-store-pwd>>
      keystore:
        type: JKS
        location: kafka/certs/kafka-keystore-preprod.jks
        password: <<key-store-pwd>>
      key:
        password: <<key-store-pwd>>
    security:
      protocol: SSL
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      compression-type: zstd #gzip, #zstd, snappy, none
      max-request-size: 15000000
logging:
  level:
    org.apache.avro: DEBUG